name: Doc

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: docusaurus/website/yarn.lock
      - run: yarn install --frozen-lockfile --no-progress
        working-directory: docusaurus/website
      - run: yarn run build
        working-directory: docusaurus/website
